name: Noob to Expert
description: Learning to Code
meta_description: "Started at the bottom, now we here (still at the bottom)"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://noob.expert'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'www.noob.expert'
author:         'Chithra Venkatesan'
